version: '3.9'

services:
    redis:
        container_name: redis
        image: redislabs/redisgraph
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        network_mode: host
        ports:
            - "6379:6379"
